NAME: Test

PRE_PROCESS: default
INPUT_CHANNEL: 1
OUTPUT_CHANNEL: 1

GAN_MODEL_TYPE: gan.Generator
DIS_MODEL_TYPE: gan.Discriminator

# GAN_MODEL_PATH: here
# DIS_MODEL_PATH: here

FONT_SIZE: 128
MAX_PADDING: 0

NUM_REFERENCE_POINTS: 4
TTF_FILE: ./utils/ttf/font1.ttf

CUDA: False
SAVE_TRAJ: False

FEEDBACK:
  WITH_FEEDBACK: True
  POST_PRORCESS:
    { CROPPING: [478, 418, 1586, 672], BINARIZE: 128, RESCALE: 0.8 }
