NAME: Test

PRE_PROCESS: default
INPUT_CHANNEL: 1
OUTPUT_CHANNEL: 1

GAN_MODEL_TYPE: gan.Generator
DIS_MODEL_TYPE: gan.Discriminator

GAN_MODEL_PATH: here
DIS_MODEL_PATH: here 

NUM_REFERENCE_POINTS: 4
TTF_FILE: 

WITH_FEEDBACK: False
CUDA: False
